version: "3.8"

services:
  runner:
    build: ./docker
    platform: linux/arm64
    restart: always
    environment:
      - REPO
      - REG_TOKEN
      - NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
