version: "3.8"

services:
  runner:
    image: custom-github-runner-mac:latest
    platform: linux/arm64
    restart: always
    environment:
      - REPO
      - REG_TOKEN
      - NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
