version: '3.8'

services:
  runner:
    image: youssefbrr/github-actions:latest # You can use this image or build your own
    restart: always
    environment:
      - REPO
      - REG_TOKEN
      - NAME